# Generated by Django 5.2.6 on 2025-10-10 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha publicación')),
                ('status', models.CharField(choices=[('DR', 'Borrador'), ('PB', 'Publicada')], default='DR', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Authorizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('student_id', models.CharField(max_length=30, unique=True, verbose_name='Carnet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Estudiante Autorizador',
                'verbose_name_plural': 'Estudiantes Autorizadores',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('student_id', models.CharField(max_length=30, unique=True, verbose_name='Carnet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Estudiante Publicador',
                'verbose_name_plural': 'Estudiantes Publicadores',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(default='Anónimo', max_length=150, verbose_name='Nombre quien comenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='revista.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='authorizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_articles', to='revista.authorizer'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='revista.publisher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revista.publisher'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
