# Generated by Django 5.2.6 on 2025-10-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_article_authorizer_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Carnet')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_publisher',
        ),
        migrations.AlterModelOptions(
            name='authorizer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
        migrations.RemoveField(
            model_name='authorizer',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='authorizer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date', models.DateField(verbose_name='Fecha de publicación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
